CREATE TABLE [fat].[Contratacao] (
    [IDFatFuncionario]                INT IDENTITY (1, 1) NOT NULL,
    [IDFuncionario]                   INT NOT NULL,
    [IDRegistro]                      INT NOT NULL,
    [IDData]                          INT NULL,
    [IDAdmissao]                      INT NULL,
    [IDCargoBasico]                   INT NULL,
    [IDCargoComissionado]             INT NULL,
    [IDDeficiencia]                   INT NULL,
    [IDEscolaridadeCargoBasico]       INT NULL,
    [IDEscolaridadeCargoComissionado] INT NULL,
    [IDReferenciaCargoBasico]         INT NULL,
    [IDReferenciaCargoComissionado]   INT NULL,
    [IDRaca]                          INT NULL,
    [IDSecretariaPrefeitura]          INT NULL,
    [IDSegmento]                      INT NULL,
    [IDSetor]                         INT NULL,
    [IDSexo]                          INT NULL,
    [IDSubgrupo]                      INT NULL,
    CONSTRAINT [PK_Fat_Funcionario] PRIMARY KEY CLUSTERED ([IDFatFuncionario] ASC),
    CONSTRAINT [FK_Dim_Admissao] FOREIGN KEY ([IDAdmissao]) REFERENCES [dim].[Admissao] ([IDAdmissao]),
    CONSTRAINT [FK_Dim_CargoBasico] FOREIGN KEY ([IDCargoBasico]) REFERENCES [dim].[CargoBasico] ([IDCargo]),
    CONSTRAINT [FK_Dim_CargoComissionado] FOREIGN KEY ([IDCargoComissionado]) REFERENCES [dim].[CargoComissionado] ([IDCargoComissionado]),
    CONSTRAINT [FK_Dim_Data] FOREIGN KEY ([IDData]) REFERENCES [dim].[Data] ([IDData]),
    CONSTRAINT [FK_Dim_Deficiencia] FOREIGN KEY ([IDDeficiencia]) REFERENCES [dim].[Deficiencia] ([IDDeficiencia]),
    CONSTRAINT [FK_Dim_EscolaridadeCargoBasico] FOREIGN KEY ([IDEscolaridadeCargoBasico]) REFERENCES [dim].[EscolaridadeCargoBasico] ([IDEscolaridade]),
    CONSTRAINT [FK_Dim_EscolaridadeCargoComissionado] FOREIGN KEY ([IDEscolaridadeCargoComissionado]) REFERENCES [dim].[EscolaridadeCargoComissionado] ([IDEscolaridadeComissionado]),
    CONSTRAINT [FK_Dim_Funcionario] FOREIGN KEY ([IDFuncionario]) REFERENCES [dim].[Funcionario] ([IDFuncionario]),
    CONSTRAINT [FK_Dim_Raca] FOREIGN KEY ([IDRaca]) REFERENCES [dim].[Raca] ([IDRaca]),
    CONSTRAINT [FK_Dim_ReferenciaCargoBasico] FOREIGN KEY ([IDReferenciaCargoBasico]) REFERENCES [dim].[ReferenciaCargoBasico] ([IDReferenciaCargoBasico]),
    CONSTRAINT [FK_Dim_ReferenciaCargoComissionado] FOREIGN KEY ([IDReferenciaCargoComissionado]) REFERENCES [dim].[ReferenciaCargoComissionado] ([IDReferenciaCargoComissionado]),
    CONSTRAINT [FK_Dim_SecretariaPrefeitura] FOREIGN KEY ([IDSecretariaPrefeitura]) REFERENCES [dim].[SecretariaPrefeitura] ([IDSecretariaPrefeitura]),
    CONSTRAINT [FK_Dim_Segmento] FOREIGN KEY ([IDSegmento]) REFERENCES [dim].[Segmento] ([IDSegmento]),
    CONSTRAINT [FK_Dim_Setor] FOREIGN KEY ([IDSetor]) REFERENCES [dim].[Setor] ([IDSetor]),
    CONSTRAINT [FK_Dim_Sexo] FOREIGN KEY ([IDSexo]) REFERENCES [dim].[Sexo] ([IDSexo]),
    CONSTRAINT [FK_Dim_Subgrupo] FOREIGN KEY ([IDSubgrupo]) REFERENCES [dim].[Subgrupo] ([IDSubGrupo])
);



